server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    absolute_redirect off;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_min_length 1024;

    location = / {
        return 301 /momo-store/;
    }

    location = /momo-store {
        return 301 /momo-store/;
    }

    location /momo-store/ {
        rewrite ^/momo-store/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
